language: generic

sudo: required

services:
    - docker

before_install:
    - docker build -t harryharanr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true harryharanr/docker-react npm run test -- --coverage